// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xetonwascehmtslrwvpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhldG9ud2FzY2VobXRzbHJ3dnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTU4NzgsImV4cCI6MjA2ODQzMTg3OH0.Ogcga7vT7V4PbrU73SjLi00FCpwGplDsXWX4O-L9Cfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});